### ISSUE TITLE
invalid_client_id: not sure if the kickstart ran?

### ISSUE THREAD

**Issue by korpiq-tiketti** [FusionAuth/fusionauth-example-nextjs-single-sign-on#3]
Pushing buttons "Log in" -> "Sign in with FusionAuth" produces the following for me:
```
{
  "error" : "invalid_client",
  "error_description" : "client_id: e9fdb985-9173-4e01-9d73-ac2d60d1dc8e is not valid.",
  "error_reason" : "invalid_client_id"
}
```

Opening http://localhost:9011 in browser redirects me to http://localhost:9011/admin/setup-wizard instead of login.

I retried a couple of times with `docker-compose down -v`.

I suspect the kickstart is not kicking in. I don't see anything about it in neither the configuration nor logs of the containers or the app.

README refers to an non-existing section: 
> "FusionAuth configuration (by hand)" section of this README describes it in detail.

Instead, I used a docker FusionAuth instance I had configured earlier. Got `Invalid redirect_uri http://localhost:3000/api/auth/callback/fusionauth` but configuring that url to redirect_uri for the target app (and matching client id and secret on FusionAuth and example app) solved it.

---

I have
- node v18.15.0
- docker-compose version 1.29.2
- Next.js v13.1.6
- on Linux x570pro 5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mooreds** [comment]
Hmmm. So there are two issues:

* we shouldn't reference configuring FusionAuth by hand. That's an old section that should be removed.
* kickstart failed to run

One thing worth noting is that kickstart sometimes takes a bit of time (one minute or so) to run, and doesn't run if there's anything in the database (any users, any api keys). Is there any chance that you might have been connecting to a database that FusionAuth had already run (because it was on the same docker volume?).

**Comment by korpiq-tiketti** [comment]
I understood from the documentation that indeed, Kickstart only runs when there's nothing on the volumes, so I ran `docker-compose down -v` and inspected that `docker-compose up` created the volumes anew. (Postgresql is not answering at localhost on the host either.)

I did not consciously wait for minutes. I remember, though, inspecting the logs of FusionAuth and wondering about how it tried mysql before settling for postgresql among other startup things, so it had some time before I tried it at least on some runs. I'll retry with a 5-minute delay soonish...

**Comment by mooreds** [comment]
Thanks @korpiq-tiketti !

**Comment by korpiq-tiketti** [comment]
Ensured there were no volumes nor even base image and built from ground up, waited 18 minutes, shut it down. Started it again, started the client app, tried to log in, got the error in screenshot. Logs attached.

(The app is not actually totally vanilla; I had chosen to log the configuration used for connection to FusionAuth, so there's that output in the log. No other changes though.)

I don't feel like there was much more I could do for this, except state again that there's nothing in the docker-compose.yml that would expose the kickstart file for the FusionAuth inside the container, so it probably can't see that.

![Screenshot_20231002_134149](https://github.com/FusionAuth/fusionauth-example-nextjs-single-sign-on/assets/125278295/997a718b-9d07-4bcb-87c1-ebbfc82d8252)
[fusionauth-vanilla-first-run.log.gz](https://github.com/FusionAuth/fusionauth-example-nextjs-single-sign-on/files/12782031/fusionauth-vanilla-first-run.log.gz)
[fusionauth-vanilla-serving-app.log.gz](https://github.com/FusionAuth/fusionauth-example-nextjs-single-sign-on/files/12782034/fusionauth-vanilla-serving-app.log.gz)
[fusionauth-vanilla-app.log.gz](https://github.com/FusionAuth/fusionauth-example-nextjs-single-sign-on/files/12782035/fusionauth-vanilla-app.log.gz)

**Comment by ghost** [comment]
Hey @korpiq-tiketti I believe our docker / kickstart was out of sync for sure, thanks for the issue!

I have made updates if you want to `git pull origin main`, let me know if you still continue to have any issues.

**Comment by korpiq-tiketti** [comment]
Thanks, now it works! I just had to wait until the docker logs said 
```
fusionauth-example-nextjs-single-sign-on-fusionauth-1  | ---------------------------------------------------------------------------------------------------------
fusionauth-example-nextjs-single-sign-on-fusionauth-1  | -------------------------------------------- Kickstarting ? --------------------------------------------
fusionauth-example-nextjs-single-sign-on-fusionauth-1  | ---------------------------------------------------------------------------------------------------------
```
